config/routes.rb
Rails.application.routes.draw do
  resources :card_likes
  resources :myedtools
  resources :edtrackers
  get 'password_resets/new'
  get 'password_resets/edit'
  post 'update_status', to: 'edtrackers#update_status'
  get 'fetch_model_form', to:'edtrackers#fetch_model_form'
  get 'fetch_model_form1', to:'myedtools#fetch_model_form1'
  get 'comment_section', to:'myedtools#comment_section'
  post 'create_ed_tool_comment', to:'myedtools#create_ed_tool_comment'
  post 'comment_delete_edtools', to:'myedtools#comment_delete_edtools'


  post 'card_liked' , to:'edtrackers#card_liked'
  delete 'card_liked_destroy' , to:'edtrackers#card_liked_destroy'
  post 'card_comment_likes' , to:'edtrackers#card_comment_likes'
  get 'comment_section_edtracker', to:'edtrackers#comment_section_edtracker'
  post 'create_comment', to:'edtrackers#create_comment'
  post 'comment_delete', to:'edtrackers#comment_delete'




  post 'card_likes_ed' , to:'myedtools#card_likes_ed'
  delete 'card_likes_destroy_ed' , to:'myedtools#card_likes_destroy_ed'
  post 'card_comment_likes_ed' , to:'myedtools#card_comment_likes_ed'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sitemap.xml.gz', to: redirect("http://s3-us-west-1.amazonaws.com/picnotes-2019/sitemaps/sitemap.xml.gz")

  post '/boards/:id/toggle_note' => 'boards#toggle_note', as: :toggle_board_note
  resources :notes do
    member do
      put 'like', to: 'notes#upvote'
      put 'dislike', to: 'notes#downvote'


    end
    collection do
      get 'chat_us', to:'chats#index'
      get 'community_interview', to: 'notes#community_interview'
      get 'contact_us', to: 'notes#contact_us'
      get 'freelance_research', to: 'notes#freelance_research'
      get 'educational_organizations', to: 'notes#educational_organizations'
      get 'what_is_picnotes', to: 'notes#what_is_picnotes'
      get 'message_from_the_founder', to: 'notes#message_from_the_founder'
      get 'sharing_your_knowledge', to: 'notes#sharing_your_knowledge'
      get 'optimizing_your_dashboard', to: 'notes#optimizing_your_dashboard'
      get 'what_type_of_topics_you_should_share', to: 'notes#what_type_of_topics_you_should_share'
      get 'communication_and_interaction', to: 'notes#communication_and_interaction'
      get 'contact_us_form', to: 'notes#contact_us_form'
      get 'add_note_to_folder', to: 'notes#add_note_to_folder'

    end
    resources :references, shallow: true, only: [:new, :create, :edit, :update, :destroy]
    resources :tags, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, shallow: true, only: [:create, :destroy]
    post '/addfolder', to: 'notes#addfolder'
    post '/create_new_folder', to: 'notes#create_new_folder'
    post 'create_comment', on: :member
    post 'comment_delete', on: :member

  end
  get 'notes/:id/add_picnotes_to_folder', to: 'notes#add_picnotes_to_folder', as: 'add_picnotes_to_folder'
  get 'comment_section_note', to:'notes#comment_section_note'
  post 'card_liked' , to:'notes#card_liked'
  delete 'card_liked_destroy' , to:'notes#card_liked_destroy'
  post 'card_comment_likes' , to:'notes#card_comment_likes'







  

  get 'terms-and-conditions', to: 'home#terms_and_conditions'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'guidelines', to: 'notes#community_guideline'
  get 'about-us', to: 'notes#about_us'
  get 'tl', to: 'notes#tl'
  get 'migrate_notes', to: 'notes#migrate_notes'
  get 'for-schools',to: 'notes#for_schools'
  get 'edfluencers',to: 'ed_fluencers#index'

  # get 'terms_and_conditions', to: 'notes#terms_and_conditions', as: 'terms-and-conditions'
  resources :messages, only:[:create]
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :ed_fluencers, :except => [:index]

  resources :folders

  resources :tags, only: [:index, :show]

  get 'search/index'


  resources :feed, only: [:index] do
    collection do
      get :user_search
      get :feed_index
    end
  end

  resource :session, only: [:index, :new, :create, :destroy, :show] do
    collection do
      get :user_notes
    end
  end

  post 'followunfollow', to: 'relationships#ajaxfollowunfollow'

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'archived_user', to: 'users#archived_user'
    end
    resources :chats, only: [:index, :show, :create]
    resources :boards
  end
  resources :flashcard_sets do
    get 'new_field', on: :collection
  end
  get 'create_flashcard', to: 'flashcard_sets#create_flashcard'

  resources :favorite_notes, only: [:create, :destroy]
  get '/favorites', to: 'favorite_notes#index', as: 'favorites'

  

  root 'notes#index'
  get 'trending', to: 'home#trending'
  get 'index', to: 'home#index'
  get 'user_search', to: 'home#user_search'
  get '/index', to: 'note#home_pagination', as: 'home_pagination'
  get 'notes_by_tag', to: 'home#notes_by_tag'
  get 'explore', to: 'notes#explore'
  resources :password_resets, only: [:new, :create, :edit, :update]

  devise_for :users, controllers: { 
  omniauth_callbacks: 'users/omniauth_callbacks',
  sessions: 'users/sessions'
 }

end

app/models/note.rb
class Note < ApplicationRecord

  attr_accessor :image, :image_cache, :remove_image

  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :favorites, as: :favorited

  has_many :references, dependent: :destroy

  acts_as_taggable_on :tags
  acts_as_votable

  belongs_to :user

  has_and_belongs_to_many :folders
  has_many :card_comment_likes, dependent: :destroy
  has_many :card_likes




  mount_uploader :image, ImageUploader

  validates(:title, {
    presence: {message: 'Must have a Title'}
  })

  validates(:body, {
    presence: true,
    length: {minimum: 2, maximum: 2000}
  })

  validates(:image, {
    presence: {message: 'Must have a Image'}
    })

    validates(:tag_list, {
      presence: {message: 'Must have a tag'}
      })

  after_initialize :set_defaults

  def self.search(search)
    if search
      note = Note.find_by(title: search)
      if note
        self.where(note_id: note)
      else
        Note.all
      end
    else
      Note.all
    end
  end

  def slug
    self.title_slug
  end

  def previous tag: nil, user: nil, picnotes_type: nil, folderid: nil, search: nil
    notes = fetch_notes(tag: tag, user: user, picnotes_type: picnotes_type, folderid: folderid, search: search)

    notes.where("notes.id < ?", id).order(id: :desc).first || notes.first
  end

  def next tag: nil, user: nil, picnotes_type: nil, folderid: nil, search: nil
    notes = fetch_notes(tag: tag, user: user, picnotes_type: picnotes_type, folderid: folderid, search: search)

    notes.where("notes.id > ?", id).order(id: :asc).first || notes.last
  end
  
  def fetch_notes tag: nil, user: nil, picnotes_type: nil, folderid: nil, search: nil
    if tag
      Note.includes(:tags).where(tags: { name: tag }).all
    elsif user && picnotes_type
      if picnotes_type == "my-picnotes"
        Note.where(user: user).order(id: :asc)
      elsif picnotes_type == "my-favorites"
        user.favorited_notes.where(archived: false).order(id: :asc)
      end
    elsif user && folderid
      folder = Folder.find(folderid)
      folder.notes.where(archived: false)
    elsif search
      notesTagged = Note.tagged_with(search, wild: true, any: true)
      tagged = notesTagged.pluck(:id)
      Note.where("title ILIKE ?", "%#{search}%").where.not(id: tagged).order(id: :asc)
    else
      Note.all
    end
  end

  private
  def set_defaults
    self.likes ||= 0
    self.dislikes ||= 0
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:add_picnotes_to_folder]
  before_action :authorize_user!, except: [:index, :trending,:notes_by_tag, :show,:create_comment, :comment_section_note, :comment_delete,:explore, :new, :create, :upvote, :community_guideline, :migrate_notes, :tl, :about_us, :contact_us, :freelance_research, :educational_organizations, :downvote, :addfolder, :empty, :terms_and_conditions, :what_is_picnotes, :message_from_the_founder, :sharing_your_knowledge, :communication_and_interaction, :optimizing_your_dashboard, :what_type_of_topics_you_should_share, :contact_us_form, :add_note_to_folder, :for_schools]

  def empty
  end

  def trending
    if params[:search].present?
      search_notes_and_users(params[:search])
      logger.debug "Users Found: #{@users.inspect}"
      respond_to do |format|
        format.html { render partial: 'searching_result', locals: { search_results: render_to_string(partial: 'searching_result', locals: { search_results: @users }) } }
        format.js { render partial: 'searching_result', locals: { search_results: render_to_string(partial: 'searching_result', locals: { search_results: @users }) } }
      end
    else
     @notes = Note.order(created_at: :desc).all
      respond_to do |format|
        format.html
        format.js { render partial: 'note' } 
      end
    end
  end

  def notes_by_tag
    if params[:tag].present?
      @tag_name = params[:tag]
      @tags = @note.tags.order(created_at: :desc)
      @references_unordered = Reference.where(note_id: @note.id)
      # @references = @references_unordered.sort_by &:file_type
      @references = @references_unordered.where(:file_type => 't')
  
      @textbooks = @references_unordered.where(:file_type => 't')
      @videos = @references_unordered.where(:file_type => 'v')
      @papers = @references_unordered.where(:file_type => 'p')
      @sources = @references_unordered.where(:file_type => 's')
  
      @reference = Reference.new
      @like = @note.likes.find_by_user_id current_user
      @dislike = @note.dislikes.find_by_user_id current_user
      @user = current_user
      @folders = Folder.where(user: current_user)
      @note_session = session[:picnotes] || []
      @note_exist = @note_session.include? @note.title_slug
      @previous_note = @note.next
      @next_note = @note.previous
      if @note_exist
        @note_index = @note_session.find_index(@note.title_slug)
        @note_index_next = @note_index + 1
        @next_note = Note.where(title_slug: @note_session[@note_index_next]).first
        @note_index_previous = @note_index - 1
        @previous_note = Note.where(title_slug: @note_session[@note_index_previous]).first
      end
      @similar = Note.tagged_with(@note.tags, :any => true)
      @meta_title = @note.title
      @meta_description = @note.body.slice(0, 120) + "..."
      @meta_keywords = @note.body
      @meta_image = @note.image.url
  
      set_meta_tags title: @meta_title, description: @meta_description, keywords: @meta_keywords
  
      respond_to do |format|
        format.js
        format.html
      end
      @notes = Note.includes(:tags).where(tags: { name: @tag_name }).all
    else
      @notes = Note.paginate(page: params[:page], per_page: 20)
    end

    respond_to do |format|
      format.js { render partial: 'note' }
      format.html { render partial: 'note' }
    end
  end

  def index
    default_meta_tags
    if params[:search]
      @notesTagged = Note.tagged_with(params[:search], wild: true, any: true)
      @users = User.where("CONCAT_WS(' ', first_name, last_name, username) ILIKE ?", "%#{params[:search]}%")
      @tagged = Array.new
      @notesTagged.each do |noteTag|
        @tagged.push(noteTag.id)
      end
      @notes = Note.where("title ILIKE ?", "%#{params[:search]}%")
      @notes = @notes.where.not(id: @tagged)
      search_notes_and_users(params[:search])
      logger.debug "Users Found: #{@users.inspect}"
      @searchresult = params[:search]
      # respond_to do |format|
      #   format.html { render partial: 'searching_result', locals: { search_results: render_to_string(partial: 'searching_result', locals: { search_results: @users }) } }
      #   format.js { render partial: 'searching_result', locals: { search_results: render_to_string(partial: 'searching_result', locals: { search_results: @users }) } }
      # end
      respond_to do |format|
        format.html
        format.js
      end
    else
      @users = []
      @notesTagged = []
      @tagged = []
      @notes = Note.order(id: :desc).paginate(page: params[:page], per_page: 20)
      Rails.logger.debug "Request format: #{request.format.symbol}"
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def comment_section_note
    @note = Note.find_by_id(params[:id])
    @comments = @note.card_comment_likes.count
    respond_to do |format|
      format.js
    end
  end

  def comment_delete
    @note = Note.find(params[:note_id])
    card_comment = CardCommentLike.find(params[:id])
    
    if card_comment.user == current_user || @note.user == current_user
      card_comment.destroy
      @comments = @note.card_comment_likes.count
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path, alert: "You are not authorized to delete this comment"
    end
  end
  def card_comment_likes
    note = Note.find(params[:note_id])
    CardCommentLike.create(note: note, user: current_user)
    respond_to do |format|
      format.js
    end
  end
  
  def create_comment
    @note = Note.find_by_id(params[:id])
    if !params["card_comment"].empty? && @note
    @note_comment = CardCommentLike.new(note_id: @note.id, body: params["card_comment"], user_id: current_user.id)
    @note_comment.save
    end
    @comments = @note.card_comment_likes.count
    respond_to do |format|
      format.js
    end
  end


  def card_liked
    @note = Note.find(params[:note_id])
    @selected_note = params[:note_id]
    card_like = @note.card_likes.where(user: current_user).last
    unless card_like.present?
      CardLike.create(note: @note, user: current_user)
    end
    respond_to do |format|
      format.js
    end
  end


  def card_liked_destroy
    @note = Note.find(params[:note_id])
    card_like = @note.card_likes.where(user: current_user).last
    if card_like.present?
      card_like.destroy
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    redirect_to root_path, alert: "Note not found" unless @note.present?

    @tags = if params[:tag].present?
      @note.tags.where(name: params[:tag])
    else
      @note.tags
    end
    @tags = @tags.order(created_at: :desc)
    @references_unordered = Reference.where(note_id: @note.id)
    # @references = @references_unordered.sort_by &:file_type
    @references = @references_unordered.where(:file_type => 't')

    @textbooks = @references_unordered.where(:file_type => 't')
    @videos = @references_unordered.where(:file_type => 'v')
    @papers = @references_unordered.where(:file_type => 'p')
    @sources = @references_unordered.where(:file_type => 's')

    @reference = Reference.new
    @like = @note.likes.find_by_user_id current_user
    @dislike = @note.dislikes.find_by_user_id current_user
    @user = current_user
    @folders = Folder.where(user: current_user)
    @note_session = session[:picnotes] || []
    @note_exist = @note_session.include? @note.title_slug

    if params.dig(:tag)
      @previous_note = @note.previous tag: params.dig(:tag)
      @next_note = @note.next tag: params.dig(:tag)
    elsif params.dig(:picnotes_type)
      @previous_note = @note.previous user: current_user, picnotes_type: params.dig(:picnotes_type)
      @next_note = @note.next user: current_user, picnotes_type: params.dig(:picnotes_type)
    elsif params.dig(:folderid)
      @previous_note = @note.previous user: current_user, folderid: params.dig(:folderid)
      @next_note = @note.next user: current_user, folderid: params.dig(:folderid)
    elsif params.dig(:search)
      @previous_note = @note.previous search: params.dig(:search)
      @next_note = @note.next search: params.dig(:search)
    else
      @previous_note = @note.next
      @next_note = @note.previous
    end
    
    # if @note_exist
    #   @note_index = @note_session.find_index(@note.title_slug)
    #   @note_index_next = @note_index + 1
    #   @next_note = Note.where(title_slug: @note_session[@note_index_next]).first
    #   @note_index_previous = @note_index - 1
    #   @previous_note = Note.where(title_slug: @note_session[@note_index_previous]).first
    # end

    @similar = Note.tagged_with(@note.tags, :any => true)
    @meta_title = @note.title
    @meta_description = @note.body.slice(0, 120) + "..."
    @meta_keywords = @note.body
    @meta_image = @note.image.url

    set_meta_tags title: @meta_title, description: @meta_description, keywords: @meta_keywords

    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @user = current_user
    @note = Note.new
  end

  def home_pagination
    
  end

  def explore
    default_meta_tags
    if params[:search].present?
      @notesTagged = Note.tagged_with(params[:search], wild: true, any: true)
      @users = User.where("CONCAT_WS(' ', first_name, last_name, username) ILIKE ?", "%#{params[:search]}%")
      @tagged = @notesTagged.pluck(:id)
      @notes = Note.where("title ILIKE ?", "%#{params[:search]}%").where.not(id: @tagged)
  
      respond_to do |format|
        format.html { render partial: 'searching_result', locals: { search_results: @notes } }
        format.js { render partial: 'searching_result', locals: { search_results: @notes } }
      end
    else
      @notes = Note.order(id: :desc).paginate(page: params[:page], per_page: 12)
      @notesTagged = []
      @tagged = []

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html copy.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 notes_col">
  <%= link_to(note_path(note.slug), { remote: true }) do %>
    <figure class="card-picknote card-product image-containermyprofile">
      <div class="image-containermyprofile">
        <%= image_tag(note.image.url(:thumb), alt: note.title, :class => "image") if note.image.present? %>
         <div class="hover-overlay">
                     <div class="overlay-content" style="margin-bottom: -13%;">
                      <p id="truncate-title" class="truncate">
                        <%= note.title %>
                      </p>
                      <p id="truncate-name" class="truncate">
                        <%= link_to "#{note.user.first_name} #{note.user.last_name}", user_path(note.user), style: 'color: inherit; text-decoration: none;' %>
                      </p>
                    </div>
                    <div class="icons" style="display: flex; justify-content: flex-end;">
                                   <span style="display: flex; gap: 4px;">
                                  <% if user_signed_in? %>
                                    <% unless current_user.favorited_notes.exists?(id: note.id) %>
                                      <span id='favorites-count-<%= note.id %>'>
                                        <%= link_to fa_icon('heart'), favorite_notes_path(note_id: note), remote: true, class: 'grey_love love_iconss', method: :post, style: 'color: red !important;' %>
                                      </span>
                                    <% else %>
                                      <span id='favorites-count-<%= note.id %>'>
                                        <%= link_to fa_icon('heart'), favorite_note_path(note), remote: true, class: 'orange_love love_iconss', method: :delete %>
                                      </span>
                                    <% end %>
                                    <span id='add-to-folder-<%= note.id %>' style="display: flex; justify-content: center; align-items: center;  margin-left: 2%;">
                                      <%= link_to "/notes/add_note_to_folder?note_id=#{note.id}", remote: true, method: :get do %>
                                        <%= image_tag 'folder-add.png', style: 'width: 35px !important; background-color: #BC171D; border-radius: 50%;' %>
                                      <% end %>
                                    </span>
                                  <% else %>
                                    <span id='add-to-folder-<%= note.id %>'>
                                      <%= link_to new_user_path do %>
                                        <span id='favorites-count-<%= note.id %>'>
                                          <%= link_to fa_icon('heart'), favorite_notes_path(note_id: note), remote: true, class: 'grey_love love_iconss', method: :post %>
                                        </span>
                                      <% end %>
                                    </span>
                                    <span id='add-to-folder-<%= note.id %>' style="display: flex; justify-content: center; align-items: center;  margin-left: 2%;">
                                      <%= link_to "/notes/add_note_to_folder?note_id=#{note.id}", remote: true, method: :get do %>
                                        <%= image_tag 'folder-add.png', style: 'width: 35px !important; background-color: #BC171D; border-radius: 50%;' %>
                                      <% end %>
                                    </span>
                                  <% end %>
                                </span>
                              </div>
                  </div>
      </div>
    </figure>
  <% end %>
</div>


<style>

.custom-heart-icon {
  color: red;
  background-color: red;
  border: 2px solid red;
  border-radius: 50%;
  padding: 5px;
  font-size: 24px;
  width: 34px;
  height: 34px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.image-containermyprofile {
  position: relative;
  overflow: hidden;
}
.card-picknote {
  width: 330px;
  border: none;
  border-radius: 15px;
  padding: 8px;
  background-color: #fff;
  position: relative;
  height: 268px;
  margin-left: auto;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.image-containermyprofile img {
  width: 100%;
  height: 100%;
  transition: transform 0.3s ease;
}
.image-containermyprofile:hover img {
  transform: scale(1.1);
}
.image-containermyprofile:hover .hover-overlay {
  opacity: 1;
}
.background-overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  background: linear-gradient(to top, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0) 90%);
  z-index: 1;
}
.hover-text {
  margin-bottom:0rem;
  margin-right: 12rem;
  font-size: 20px;
  color: white;
  font-weight: bold;
  z-index: 2;
  margin-top:0px !important;
  text-decoration: none;

}
.hover-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 20%;
  display: flex;
  flex-direction: column; /* Stack items vertically */
  justify-content: center; /* Align items to the bottom */
  opacity: 0;
  transition: opacity 0.3s ease;
  padding: 1rem 1rem 0 1rem;
  box-sizing: border-box;
  z-index: 2;
}

.overlay-content {
  margin-bottom: -17%;
  display: flex;
  flex-direction: column; /* Stack title and name vertically */
  align-items: flex-start; /* Align items to the left */
  margin-bottom: 10px; /* Add spacing between elements */
}

.truncate {
  display: inline-block;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 20ch;
  color: white !important;
  font-weight: bold;
  font-size: 11px;
  text-decoration: none;
}

.icons {
  display: flex;
  gap: 5px;
  z-index: 3;
}

.icons span {
  position: relative;
  z-index: 3;
}

</style>

<script>
  function truncateText(id, maxLength) {
  var element = document.getElementById(id);
  if (element && element.textContent.length > maxLength) {
    element.textContent = element.textContent.slice(0, maxLength) + '...';
  }
}

document.addEventListener("DOMContentLoaded", function() {
  truncateText('truncate-title', 10); 
  truncateText('truncate-name', 10);
});

</script>

app/views/notes/_overlay_buttons.html.erb
<div class="middle">
  <div>
    <div class="container" style="margin-left: 29px;">
      <div class="row" style="background-color: #ffffff;">
        <% if user_signed_in?%>
          <% unless current_user.favorited_notes.exists?(id: note.id) %>
            <div class="col-sm-4"><span id = 'favorites-count-<%=note.id%>'>
                  <%= link_to fa_icon('heart-o'), favorite_notes_path(note_id: note), remote:true, method: :post %>
              </span></div>
          <% else %>
            <div class="col-sm-4"><span id ='favorites-count-<%=note.id%>'>
                 <%= link_to fa_icon('heart'), favorite_note_path(note), remote:true, method: :delete %>
                </span></div>&nbsp;
          <% end %>
          <div class="col-sm-4" style="padding-left: 22px;">  <span id = 'add-to-folder-<%=note.id %>'>
            <%= link_to fa_icon('plus'), add_note_to_folder_notes_path(note_id: note), remote:true, method: :get %>
          </span></div>&nbsp;
        <% end %>
        <% unless user_signed_in?%>
          <div class="col-sm-4">  <span id = 'add-to-folder-<%note.id %>'><a href="#" data-parent="#panel" data-toggle='modal' data-target="#newSessionModal", data-whatever='@mdo'><%=fa_icon('heart-o') %></a></span></div>
          <div class="col-sm-4" style="padding-left: 22px;">  <span id = 'add-to-folder-<%note.id %>'><a  href="#" data-parent="#panel" data-toggle='modal' data-target="#newSessionModal", data-whatever='@mdo'><%=fa_icon('plus') %></a></span></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/downvote.js.erb
$('.upvotes-count').html('<%= @note.get_upvotes.size %>')

$('.downvotes-count').html('<%= @note.get_downvotes.size %>')
$('#loader').addClass('hidden');

app/views/notes/empty.html.erb
<div style = 'text-align: center; margin-top: 30px; width: 100%;'>
  <p> Results for #<%= @searchresult %> </p>
</div>

app/views/notes/freelance_research.html.erb
<style>


</style>
<body>
<div class='profile-dashboard'>
  <br>
  <div class="profile-menu">
    <p> <%= link_to 'About Us', about_us_path, class: "current profile-links set-font-family" %> </p>
    <p> <%= link_to 'Community Guidelines', guidelines_path, class: " profile-links set-font-family" %>
    <p> <%= link_to 'Terms and Conditions', terms_and_conditions_path, class: " profile-links set-font-family" %>
    <p> <%= link_to 'Contact Us', contact_us_notes_path, class: " profile-links set-font-family" %>
  </div>
</div>
<br>
<div class="container-fluid " style=" padding-right: 56px;" data-turbolinks="false">
  <div class="row">
    <div class="col-sm-3 about-us-col-sm-3 nav-justified " id="spy">
      <div class="nav-fill nav-pillse flex-column set-font-family">
        <!--        <li class="nav-item"><a class="nav-link active text-bold fo-bold " id="g" href="#e"><h5>Our Starting Point</h5></a></li>-->
        <i class="nav-item">

          <a class="nav-link footer-color " href="/notes/what_is_picnotes"><h5 class="text ">What is Picnotes?</h5></a>
        </i>
        <i class="nav-item"><a class="nav-link footer-color " href="/notes/educational_organizations"><h5 class="edu">Picnotes Edu.</h5></a>
        </i>
        <i class="nav-item"><a class="nav-link footer-color current " href="/notes/freelance_research"><h5 class="fre bold">Freelance Researching</h5></a></i>
        <i class="nav-item"><a class="nav-link footer-color " href="/notes/message_from_the_founder"><h5 class="msg">Message from the Founder</h5></a>
        </i>
      </div>
    </div>
    <div class=" col-sm-9  scrollspy-example vertical-line"  data-spy="scroll" data-spy="scroll" data-target="#spy">
      <div class="set-font-family" id="c">
        <h1 class="font-size-h4">Freelance Researching</h1>
        <p>
          <b>Coming Soon</b></p>
      </div>
    </div>
  </div>
</div>
<!-- ClickDesk Live Chat Service for websites -->
<script type='text/javascript'>
    var glc = _glc || [];
    glc.push('all_ag9zfmNsaWNrZGVza2NoYXRyEgsSBXVzZXJzGICAkIPm6qALDA');
    var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' :
        'http://my.clickdesk.com/clickdesk-ui/browser/');
    var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
    var glcspt = document.createElement('script');
    glcspt.type = 'text/javascript';
    glcspt.async = true;
    glcspt.src = glcpath + 'livechat-new.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(glcspt, s);
</script>
<!-- End of ClickDesk -->

</body>