config/routes.rb
Rails.application.routes.draw do
  resources :card_likes
  resources :myedtools
  resources :edtrackers
  get 'password_resets/new'
  get 'password_resets/edit'
  post 'update_status', to: 'edtrackers#update_status'
  get 'fetch_model_form', to:'edtrackers#fetch_model_form'
  get 'fetch_model_form1', to:'myedtools#fetch_model_form1'
  get 'comment_section', to:'myedtools#comment_section'
  post 'create_ed_tool_comment', to:'myedtools#create_ed_tool_comment'
  post 'comment_delete_edtools', to:'myedtools#comment_delete_edtools'


  post 'card_liked' , to:'edtrackers#card_liked'
  delete 'card_liked_destroy' , to:'edtrackers#card_liked_destroy'
  post 'card_comment_likes' , to:'edtrackers#card_comment_likes'
  get 'comment_section_edtracker', to:'edtrackers#comment_section_edtracker'
  post 'create_comment', to:'edtrackers#create_comment'
  post 'comment_delete', to:'edtrackers#comment_delete'




  post 'card_likes_ed' , to:'myedtools#card_likes_ed'
  delete 'card_likes_destroy_ed' , to:'myedtools#card_likes_destroy_ed'
  post 'card_comment_likes_ed' , to:'myedtools#card_comment_likes_ed'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sitemap.xml.gz', to: redirect("http://s3-us-west-1.amazonaws.com/picnotes-2019/sitemaps/sitemap.xml.gz")

  post '/boards/:id/toggle_note' => 'boards#toggle_note', as: :toggle_board_note
  resources :notes do
    member do
      put 'like', to: 'notes#upvote'
      put 'dislike', to: 'notes#downvote'


    end
    collection do
      get 'chat_us', to:'chats#index'
      get 'community_interview', to: 'notes#community_interview'
      get 'contact_us', to: 'notes#contact_us'
      get 'freelance_research', to: 'notes#freelance_research'
      get 'educational_organizations', to: 'notes#educational_organizations'
      get 'what_is_picnotes', to: 'notes#what_is_picnotes'
      get 'message_from_the_founder', to: 'notes#message_from_the_founder'
      get 'sharing_your_knowledge', to: 'notes#sharing_your_knowledge'
      get 'optimizing_your_dashboard', to: 'notes#optimizing_your_dashboard'
      get 'what_type_of_topics_you_should_share', to: 'notes#what_type_of_topics_you_should_share'
      get 'communication_and_interaction', to: 'notes#communication_and_interaction'
      get 'contact_us_form', to: 'notes#contact_us_form'
      get 'add_note_to_folder', to: 'notes#add_note_to_folder'

    end
    resources :references, shallow: true, only: [:new, :create, :edit, :update, :destroy]
    resources :tags, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, shallow: true, only: [:create, :destroy]
    post '/addfolder', to: 'notes#addfolder'
    post '/create_new_folder', to: 'notes#create_new_folder'
    post 'create_comment', on: :member
    post 'comment_delete', on: :member

  end
  get 'notes/:id/add_picnotes_to_folder', to: 'notes#add_picnotes_to_folder', as: 'add_picnotes_to_folder'
  get 'comment_section_note', to:'notes#comment_section_note'
  post 'card_liked' , to:'notes#card_liked'
  delete 'card_liked_destroy' , to:'notes#card_liked_destroy'
  post 'card_comment_likes' , to:'notes#card_comment_likes'







  

  get 'terms-and-conditions', to: 'home#terms_and_conditions'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'guidelines', to: 'notes#community_guideline'
  get 'about-us', to: 'notes#about_us'
  get 'tl', to: 'notes#tl'
  get 'migrate_notes', to: 'notes#migrate_notes'
  get 'for-schools',to: 'notes#for_schools'
  get 'edfluencers',to: 'ed_fluencers#index'

  # get 'terms_and_conditions', to: 'notes#terms_and_conditions', as: 'terms-and-conditions'
  resources :messages, only:[:create]
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :ed_fluencers, :except => [:index]

  resources :folders

  resources :tags, only: [:index, :show]

  get 'search/index'


  resources :feed, only: [:index] do
    collection do
      get :user_search
      get :feed_index
    end
  end

  resource :session, only: [:index, :new, :create, :destroy, :show] do
    collection do
      get :user_notes
    end
  end

  post 'followunfollow', to: 'relationships#ajaxfollowunfollow'

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'archived_user', to: 'users#archived_user'
    end
    resources :chats, only: [:index, :show, :create]
    resources :boards
  end
  resources :flashcard_sets do
    get 'new_field', on: :collection
  end
  get 'create_flashcard', to: 'flashcard_sets#create_flashcard'

  resources :favorite_notes, only: [:create, :destroy]
  get '/favorites', to: 'favorite_notes#index', as: 'favorites'

  

  root 'notes#index'
  get 'trending', to: 'home#trending'
  get 'index', to: 'home#index'
  get 'user_search', to: 'home#user_search'
  get '/index', to: 'note#home_pagination', as: 'home_pagination'
  get 'notes_by_tag', to: 'home#notes_by_tag'
  get 'explore', to: 'notes#explore'
  resources :password_resets, only: [:new, :create, :edit, :update]

  devise_for :users, controllers: { 
  omniauth_callbacks: 'users/omniauth_callbacks',
  sessions: 'users/sessions'
 }

end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  has_and_belongs_to_many :notes

  def add_note(note)
    self.notes.push(note)
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:user_id]
      # if params[:user_id] != current_user.id.to_s
      user = User.find_by(id: params[:user_id])
      @user = user
      @folders = Folder.where(user: user)
    else
      @user = current_user
      @folders = Folder.where(user: current_user)
    end
  end

  def show
    if params[:user_id]
      # if params[:user_id] != current_user.id.to_s
      user = User.find_by(id: params[:user_id])
      @user = user
      @folder = Folder.find(params[:id])
    else
      @user = current_user
      @folder = Folder.find(params[:id])
    end
    @notes = @folder.notes.where(archived: false).order(id: :asc)

    @count = 0
    my_array = []
    @notes.each do |favorite|
      @count = @count + 1
      if @count < 15
        my_array.push favorite.title_slug
      end
    end
    session[:picnotes] = my_array
  end

  def new
    @user = current_user
    @folder = Folder.new
  end
  def create
    @user = current_user
    @folder = Folder.new(folder_params)
    @folder.user = @user
  
    respond_to do |format|
      if @folder.save
        format.html { redirect_to feed_index_path }
        format.js { render 'create_success', locals: { folder: @folder } }
      else
        format.html { render :new }
        format.js { render 'create_failure', locals: { errors: @folder.errors.full_messages } }
      end
    end
  end
  

  def destroy

    @folder = Folder.find(params[:id])
    @folder.destroy
    redirect_to feed_index_path
  end

  private

  def folder_params
    params.require(:folder).permit(:name, :user_id)
  end
end

app/views/folders/_index.html copy.erb
<% if @user == current_user %>
  <%= render './modals/new_folder_modal' %>
<% else %>
  <%= render './modals/new_folder_modal' %>
<% end %>

<% if @folders.count > 0 %>

  <div>
    <% if @user == current_user %>
      <button class=" add-picnotes btn btn-custom btn-block custom-btn-sm" id="newFolderModal" data-bs-toggle="modal" data-bs-target="#newFolderModal" style="display:flex;margin-bottom:20px; justify-content:center;margin-top:20px; width: 20%">Create New Folder</button>

      
      <div class="notes-container-grid">
        <% if @folders.count > 0 %>
          <div class="folder-container-grid row">

            <% @folders.each do |folder| %>
            <div class="folder-container col-lg-3">
              <div class="folder-header d-flex justify-content-between align-items-center" style="padding-top: 10px;">
                <%= link_to(folder_path(folder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'blue-appearance-btn delete-btn') do %>
                  <%= image_tag('deleteIcon.png', alt: 'Delete', class: 'delete-icon') %>
                <% end %>
                <div class="folder-title-container">
                  <h1 class="mobile-font note-btn-font title">
                    <%= truncate(folder.name, length: 40) %>
                  </h1>
                </div>
              </div>
              <div class="folder-content" style="margin-bottom: 200px;">
                <%= link_to(folder_path(folder, user_id: @user)) do %>
                  <div class="grid-folder mb-1" style="margin-right: 17%; margin-left: -8%;">
                    <% folder.notes.where(archived: false).each_with_index do |note, i| %>
                      <% if i < 6 %>
                        <div class='board-test-image'>
                          <% if note.image.url.length > 0 %>
                            <%= image_tag note.image.url(:board_thumb), class: 'image-size' %>
                          <% else %>
                            <%= image_tag 'empty.png', class: 'image-size' %>
                          <% end %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>

    <% else %>


      <div class="notes-container-grid">
        <% if @folders.count > 0 %>
           <div class="folder-container-grid row">

            <% @folders.each do |folder| %>
            <div class="folder-container col-lg-3">
              <div class="folder-header d-flex justify-content-between align-items-center" style="padding-top: 10px;">
              </div>
              <div class="folder-content" style="margin-bottom: 200px;">
                <%= link_to(folder_path(folder, user_id: @user)) do %>
                    <h1 class="mobile-font note-btn-font title" style="display: flex;">
              <%= truncate(folder.name, length: 40) %>
            </h1>
                  <div class="grid-folder mb-1" style="margin-right: 0%; margin-left: 0%; margin-top: 6%">
                    <% folder.notes.where(archived: false).each_with_index do |note, i| %>
                      <% if i < 6 %>
                        <div class='board-test-image'>
                          <% if note.image.url.length > 0 %>
                            <%= image_tag note.image.url(:board_thumb), class: 'image-size' %>
                          <% else %>
                            <%= image_tag 'empty.png', class: 'image-size' %>
                          <% end %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>

      </div>
    <% end %>

  </div>
<% else %>
  <div class='empty' style='justify-content: center !important; display: flex; margin-top: 16%'>
    <%= image_tag 'empty-board.png', style: 'width: 20%;' %>
  </div>
  <p style="justify-content: center !important; display: flex;">You have not created any folder yet.</p ><span style="justify-content: center !important; display: flex;">See how to create a folder.</span>
  <button class="btn btn-custom btn-block custom-btn-sm mid-picnotes" id="newFolderModal" data-bs-toggle="modal" data-bs-target="#newFolderModal" >Create New Folder</button>

<% end %>


<style>
  /* Custom button styles */
.btn-custom {
  display: flex;
  justify-content: center;
  margin-bottom: 20px;
  margin-top: 20px;
}

/* Responsive button width */
@media (min-width: 576px) { /* Extra small devices (phones, 576px and up) */
  .btn-custom {
    width: 50%;
  }
}

@media (min-width: 768px) { /* Small devices (tablets, 768px and up) */
  .btn-custom {
    width: 40%;
  }
}

@media (min-width: 992px) { /* Medium devices (desktops, 992px and up) */
  .btn-custom {
    width: 30%;
  }
}

@media (min-width: 1200px) { /* Large devices (large desktops, 1200px and up) */
  .btn-custom {
    width: 20%;
  }
}

  .folder-container {
  display: flex;
  flex-direction: column;
  border: 1px solid #ddd; /* Optional, for visual debugging */
  padding: 10px;
  margin-bottom: 20px; /* Adjust as needed */
}

.folder-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.delete-btn {
  flex-shrink: 0;
}

.delete-icon {
  width: 24px; /* Adjust the size as needed */
}

.folder-title-container {
  /* flex-grow: 1;
  padding-left: 10px; */
}

.grid-folder {
  margin-right: 8%;
    margin-top: 20%;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

.board-test-image {
  border: 1px solid #ddd; /* Optional, for visual debugging */
  padding: 5px; /* Adjust as needed */
}

.image-size {
  width: 100%; /* Ensure images are responsive */
}

@media (max-width: 992px) {
  .grid-folder {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 576px) {
  .grid-folder {
    grid-template-columns: 1fr;
  }
}

.add-picnotes {
  display: flex;
  height: 40px;
  width: 15%;
  margin-left:auto;
  margin-right:20px;
  color: white !important;
}
.mid-picnotes{
    display: flex;
    height: 40px;
    width: 20%;
    justify-content: center !important;
    margin-left: 40%;
    margin-top: 10px;
    color: white !important;

  }

.note-container-text-fold{
    word-wrap: break-word;
    overflow: hidden;
    line-height: 1.2em;
    height: 2.4em;
    color: #666;
    display: flex;
    width: 70%;
}
.folder-container-grid {
  display: flex;
  flex-wrap: wrap;
  padding: 10px;
  max-width: 100% ;
}

.col-lg-3{
      max-width: 24% !important;
}

.folder-container{
    margin-top: 20px;
    background-color: #f0f0f0;
    padding: 20px;
    border-radius: 10px;
    width: 296px;
    position: relative;
    height: 244px;
}


.title {
    font-family: Cako, sans-serif;
    font-size: 18px;
    font-weight: 400;
    line-height: 21.6px;
    text-align: right;
    margin-bottom: 10px;
}

.delete-btn {
    position: absolute;
    top: 20px;
    right: 20px;
    background: none;
    border: none;
    cursor: pointer;
    font-size: 18px;
}
.grid-folder{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}
.board-test-image img{
    width: 100%;
    border-radius: 5px;

}
</style>

app/views/folders/_index.html.erb
<% if @user == current_user %>
  <%= render './modals/new_folder_modal' %>
<% else %>
  <%= render './modals/new_folder_modal' %>
<% end %>

<% if @folders.count > 0 %>

  <div>
    <button class=" add-picnotes btn btn-custom btn-block custom-btn-sm" id="newFolderModal" data-bs-toggle="modal" data-bs-target="#newFolderModal" style="display:flex;margin-bottom:20px; justify-content:center;margin-top:20px; width: 20%">Create New Folder</button>
    <div class="notes-container-grid">
      <% if @folders.count > 0 %>
        <div class="folder-container-grid row">

          <% @folders.each do |folder| %>
          <div class="folder-container col-lg-3 col-md-4">
            <div class="folder-header d-flex justify-content-between align-items-center" style="padding-top: 10px;">
              <%= link_to(folder_path(folder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'blue-appearance-btn delete-btn') do %>
                <%= image_tag('deleteIcon.png', alt: 'Delete', class: 'delete-icon') %>
              <% end %>
              <div class="folder-title-container">
                <h1 class="mobile-font note-btn-font title">
                  <%= folder.name %>
                </h1>
              </div>
            </div>

            <div class="row">
              <% folder.notes.where(archived: false).order(id: :asc).each_with_index do |note, i| %>
                <% if i < 8 %>
                <div class="col-lg-3 col-md-3 folder-note <%= 'last-note' if i == 7 %>">
                  <% if note.image.url.length > 0 %>
                    
                    <%= link_to(folder_path(folder, user_id: @user)) do %>
                      <%= image_tag note.image.url(:board_thumb), class: "image-size " %>
                      <% if i == 7 %>
                        <span>+<%= folder.notes.size - i %></span>
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= image_tag 'empty.png', class: 'image-size' %>
                  <% end %>
                </div>
                <% end %>
              <% end %>
            </div>
            
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class='empty' style='justify-content: center !important; display: flex; margin-top: 16%'>
    <%= image_tag 'empty-board.png', style: 'width: 20%;' %>
  </div>
  <p style="justify-content: center !important; display: flex;">You have not created any folder yet.</p ><span style="justify-content: center !important; display: flex;">See how to create a folder.</span>
  <button class="btn btn-custom btn-block custom-btn-sm mid-picnotes" id="newFolderModal" data-bs-toggle="modal" data-bs-target="#newFolderModal" >Create New Folder</button>

<% end %>


<style>
  /* Custom button styles */
.btn-custom {
  display: flex;
  justify-content: center;
  margin-bottom: 20px;
  margin-top: 20px;
}

/* Responsive button width */
@media (min-width: 576px) { /* Extra small devices (phones, 576px and up) */
  .btn-custom {
    width: 50%;
  }
}

@media (min-width: 768px) { /* Small devices (tablets, 768px and up) */
  .btn-custom {
    width: 40%;
  }
}

@media (min-width: 992px) { /* Medium devices (desktops, 992px and up) */
  .btn-custom {
    width: 30%;
  }
}

@media (min-width: 1200px) { /* Large devices (large desktops, 1200px and up) */
  .btn-custom {
    width: 20%;
  }
}

  .folder-container {
  display: flex;
  flex-direction: column;
  border: 1px solid #ddd; /* Optional, for visual debugging */
  padding: 10px;
  margin-bottom: 20px; /* Adjust as needed */
}

.folder-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.delete-btn {
  flex-shrink: 0;
}

.delete-icon {
  width: 24px; /* Adjust the size as needed */
}

.folder-title-container {
  /* flex-grow: 1;
  padding-left: 10px; */
}

.grid-folder {
  margin-right: 8%;
    margin-top: 20%;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

.board-test-image {
  border: 1px solid #ddd; /* Optional, for visual debugging */
  padding: 5px; /* Adjust as needed */
}

.image-size {
  width: 100%; /* Ensure images are responsive */
}

@media (max-width: 992px) {
  .grid-folder {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 576px) {
  .grid-folder {
    grid-template-columns: 1fr;
  }
}

.add-picnotes {
  display: flex;
  height: 40px;
  width: 15%;
  margin-left:auto;
  margin-right:20px;
  color: white !important;
}
.mid-picnotes{
    display: flex;
    height: 40px;
    width: 20%;
    justify-content: center !important;
    margin-left: 40%;
    margin-top: 10px;
    color: white !important;

  }

.note-container-text-fold{
    word-wrap: break-word;
    overflow: hidden;
    line-height: 1.2em;
    height: 2.4em;
    color: #666;
    display: flex;
    width: 70%;
}
.folder-container-grid {
  display: flex;
  flex-wrap: wrap;
  padding: 10px;
  max-width: 100% ;
}

.col-lg-3{
      max-width: 24% !important;
}

.folder-container{
    margin-top: 20px;
    background-color: #f0f0f0;
    padding: 20px;
    border-radius: 10px;
    width: 296px;
    position: relative;
    height: 244px;
}


.title {
    font-family: Cako, sans-serif;
    font-size: 18px;
    font-weight: 400;
    line-height: 21.6px;
    text-align: right;
    margin-bottom: 10px;
}

.delete-btn {
    position: absolute;
    top: 20px;
    right: 20px;
    background: none;
    border: none;
    cursor: pointer;
    font-size: 18px;
}
.grid-folder{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}
.board-test-image img{
    width: 100%;
    border-radius: 5px;

}

.folder-note{
  padding: 0 !important;
}

.folder-note img {
  padding: 3px !important;
  border-radius: 15px;
}

.last-note:last-child span {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: rgba(0, 0, 0, 0.6);
  color: white;
  font-weight: bold;
  padding: 5px 10px;
  border-radius: 5px;
  font-size: 0.8rem;
  text-align: center;
  z-index: 1;
}

.last-note:last-child img {
  opacity: 0.9;
  filter: blur(0.5px);
}
</style>

app/views/folders/create_failure.js.erb
console.log('Folder creation failed');
alert('Error: <%= j errors.join(", ") %>');
$('#loader').addClass('hidden');

app/views/folders/create_success.js.erb
$('#newFolderModal').modal('hide'); 
var newFolderOption = $('<option>', {
  value: '<%= @folder.id %>',
  text: '<%= @folder.name %>'
});
$('#add_picnote_to_folder_form select[name="folder_id"]').append(newFolderOption);


var folderCount = $('#add_picnote_to_folder_form select[name="folder_id"] option').length;

if (folderCount > 0) {
  $('.empty').hide();
  $('.modal-body').show();

  $('#add_picnote_to_folder_form select[name="folder_id"]').show();
} else {
  $('#add_picnote_to_folder_form select[name="folder_id"]').show();
}

$('#loader').addClass('hidden');

app/views/folders/index.js.erb
$("#profileDetails").html("<%= j render partial: 'folders/index' %>");
$('#loader').addClass('hidden');

app/views/folders/new.html.erb
<%= simple_form_for @folder do |form| %>
  <%= form.label :name, 'Title (Required)' %>
  <%= form.input :name, label: false %>
  <div class = 'form-btn-container text-center'>
    <%= form.button :submit, :class => 'blue-appearance-btn' %>
  </div>
<% end %>

app/views/folders/show.html.erb
<% if current_user == @user && current_user != nil && @user != nil && current_user.id == @folder.user_id %>
  <div style='text-align: center;'>
    <h2> Folder Name: <strong> <%= @folder.name %> </strong></h2>
    <%= link_to('Delete', folder_path(@folder), class: 'blue-appearance-btn', data: {confirm: 'Are you sure?'}, method: :delete) %>
  </div>
<% else %>
  <div style='text-align: center;'>
    <h1> Folder Name: <strong> <%= @folder.name %> </strong></h1>
    <%#= link_to('Delete', folder_path(@folder), class: 'blue-appearance-btn', data: {confirm: 'Are you sure?'}, method: :delete) %>
  </div>
<% end %>

<div id="note-content"></div>
<div class="row" id="noteContent"></div>

<div class='flex-center'>
  <div class="notes-container" style='margin-top: 20px;'>
    <% @notes.each do |note| %>
      <%= render partial: 'notes/note_general', locals: {note: note, folderid: @folder.id} %>
  <% end %>
  </div>
</div>

<div class="profileDetails" style="display: none;">
  <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" style="background-color: white">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-lg-0">
          
          <li class="nav-item"  >
            <%= link_to feed_index_feed_index_path, remote: true, class: "profile-links nav-link", id: "my-feeds-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'box.png', size: '18x18' %>
              <span style="font-weight:400;">Feed</span>
            <% end %>
          </li>


          <li class="nav-item"  >
            <%= link_to user_notes_session_path, remote: true, class: "profile-links nav-link", id: "my-picnotes-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'note.png', size: '24x24' %>
              <span style="font-weight:400;">Picnotes</span>
              <span class='note-count'><%= "(#{@user.notes.where(archived: false).count})" %></span>
            <% end %>
          </li>

          <li class="nav-item"  >
            <%= link_to folders_path(current_user), remote: true, class: "profile-links nav-link", id: "my-folders-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'myfolder.png', size: '24x24' %>
              <span style="font-weight:400; font-size: 14px;">
              <%= (@folders.size rescue 0) > 0 ? 'Folders' : 'Folder' %>
              </span>
              <span class='note-count'><%= "(#{@user.folders.count})" %></span>
            <% end %>
          </li>

          <li class="nav-item"  >
            <%= link_to favorites_path, remote: true, class: "profile-links nav-link", id: "my-favorites-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'heart.png', size: '24x24' %>
              <span style="font-weight:400; font-size: 14px;">
                <%= (@favorites.size rescue 0) > 0 ? 'Favorites' : 'Favorite' %>
              </span>
              <span class='note-count'><%="(#{ @user.favorited_notes.where(archived: false).count})" %></span>
            <% end %>
          </li>

          <li class="nav-item" >
            <%= link_to create_flashcard_path(id: current_user), remote: true, class: "profile-links nav-link", id: "my-flashcards-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'flashcard.png', size: '24x24' %>
              <span style="font-weight:400; font-size: 14px;">Flashcards</span>
            <% end %>
          </li>
          <li class="nav-item"  >
            <%= link_to new_edtracker_path(id: current_user), remote: true, class: "profile-links nav-link", id: "my-edtracker-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'attach.png', size: '24x24' %>
              <span style="font-weight:400; font-size: 14px;">EdTracker</span>
            <% end %>
          </li>
          <li class="nav-item"  >
            <%= link_to new_myedtool_path(id: current_user), remote: true, class: "profile-links nav-link", id: "my-edtools-link", data: { action: 'click->profile#loadContent', target: 'profile.picnotesLink' } do %>
              <%= image_tag 'files.png', size: '24x24' %>
              <span style="font-weight:400; font-size: 14px;">EdTools</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="row" id="profileDetails">
  </div>
</div>


<style>
#folder-picnote{
  margin-bottom:-12% !important;
}

</style>