config/routes.rb
Rails.application.routes.draw do
  resources :card_likes
  resources :myedtools
  resources :edtrackers
  get 'password_resets/new'
  get 'password_resets/edit'
  post 'update_status', to: 'edtrackers#update_status'
  get 'fetch_model_form', to:'edtrackers#fetch_model_form'
  get 'fetch_model_form1', to:'myedtools#fetch_model_form1'
  get 'comment_section', to:'myedtools#comment_section'
  post 'create_ed_tool_comment', to:'myedtools#create_ed_tool_comment'
  post 'comment_delete_edtools', to:'myedtools#comment_delete_edtools'


  post 'card_liked' , to:'edtrackers#card_liked'
  delete 'card_liked_destroy' , to:'edtrackers#card_liked_destroy'
  post 'card_comment_likes' , to:'edtrackers#card_comment_likes'
  get 'comment_section_edtracker', to:'edtrackers#comment_section_edtracker'
  post 'create_comment', to:'edtrackers#create_comment'
  post 'comment_delete', to:'edtrackers#comment_delete'




  post 'card_likes_ed' , to:'myedtools#card_likes_ed'
  delete 'card_likes_destroy_ed' , to:'myedtools#card_likes_destroy_ed'
  post 'card_comment_likes_ed' , to:'myedtools#card_comment_likes_ed'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sitemap.xml.gz', to: redirect("http://s3-us-west-1.amazonaws.com/picnotes-2019/sitemaps/sitemap.xml.gz")

  post '/boards/:id/toggle_note' => 'boards#toggle_note', as: :toggle_board_note
  resources :notes do
    member do
      put 'like', to: 'notes#upvote'
      put 'dislike', to: 'notes#downvote'


    end
    collection do
      get 'chat_us', to:'chats#index'
      get 'community_interview', to: 'notes#community_interview'
      get 'contact_us', to: 'notes#contact_us'
      get 'freelance_research', to: 'notes#freelance_research'
      get 'educational_organizations', to: 'notes#educational_organizations'
      get 'what_is_picnotes', to: 'notes#what_is_picnotes'
      get 'message_from_the_founder', to: 'notes#message_from_the_founder'
      get 'sharing_your_knowledge', to: 'notes#sharing_your_knowledge'
      get 'optimizing_your_dashboard', to: 'notes#optimizing_your_dashboard'
      get 'what_type_of_topics_you_should_share', to: 'notes#what_type_of_topics_you_should_share'
      get 'communication_and_interaction', to: 'notes#communication_and_interaction'
      get 'contact_us_form', to: 'notes#contact_us_form'
      get 'add_note_to_folder', to: 'notes#add_note_to_folder'

    end
    resources :references, shallow: true, only: [:new, :create, :edit, :update, :destroy]
    resources :tags, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, shallow: true, only: [:create, :destroy]
    post '/addfolder', to: 'notes#addfolder'
    post '/create_new_folder', to: 'notes#create_new_folder'
    post 'create_comment', on: :member
    post 'comment_delete', on: :member

  end
  get 'notes/:id/add_picnotes_to_folder', to: 'notes#add_picnotes_to_folder', as: 'add_picnotes_to_folder'
  get 'comment_section_note', to:'notes#comment_section_note'
  post 'card_liked' , to:'notes#card_liked'
  delete 'card_liked_destroy' , to:'notes#card_liked_destroy'
  post 'card_comment_likes' , to:'notes#card_comment_likes'







  

  get 'terms-and-conditions', to: 'home#terms_and_conditions'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'guidelines', to: 'notes#community_guideline'
  get 'about-us', to: 'notes#about_us'
  get 'tl', to: 'notes#tl'
  get 'migrate_notes', to: 'notes#migrate_notes'
  get 'for-schools',to: 'notes#for_schools'
  get 'edfluencers',to: 'ed_fluencers#index'

  # get 'terms_and_conditions', to: 'notes#terms_and_conditions', as: 'terms-and-conditions'
  resources :messages, only:[:create]
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  resources :ed_fluencers, :except => [:index]

  resources :folders

  resources :tags, only: [:index, :show]

  get 'search/index'


  resources :feed, only: [:index] do
    collection do
      get :user_search
      get :feed_index
    end
  end

  resource :session, only: [:index, :new, :create, :destroy, :show] do
    collection do
      get :user_notes
    end
  end

  post 'followunfollow', to: 'relationships#ajaxfollowunfollow'

  resources :relationships

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'archived_user', to: 'users#archived_user'
    end
    resources :chats, only: [:index, :show, :create]
    resources :boards
  end
  resources :flashcard_sets do
    get 'new_field', on: :collection
  end
  get 'create_flashcard', to: 'flashcard_sets#create_flashcard'

  resources :favorite_notes, only: [:create, :destroy]
  get '/favorites', to: 'favorite_notes#index', as: 'favorites'

  

  root 'notes#index'
  get 'trending', to: 'home#trending'
  get 'index', to: 'home#index'
  get 'user_search', to: 'home#user_search'
  get '/index', to: 'note#home_pagination', as: 'home_pagination'
  get 'notes_by_tag', to: 'home#notes_by_tag'
  get 'explore', to: 'notes#explore'
  resources :password_resets, only: [:new, :create, :edit, :update]

  devise_for :users, controllers: { 
  omniauth_callbacks: 'users/omniauth_callbacks',
  sessions: 'users/sessions'
 }

end

app/views/modals/_ed_tracker_modal.html.erb
<div class="modal fade" id='edtrackerModal' tabindex="-1" role="dialog" aria-labelledby="editSessionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="min-width: 550px;padding: 20px; border-radius: 2%;">
      <div class="modal-header d-flex justify-content-center position-relative" style="border-bottom: none;">
        <h5 class="modal-title text-black" id="edtrackerModal" style="margin-left: auto; margin-top: 2rem; justify-content: center; font-size:26px;font-style:Cako;font-weight:400; line-height:32px;">
          I want to learn
        </h5>
        <button style="margin-top: -130px; margin-right: -45px;" type="button" onclick="kill_model()" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div style="margin-top: 1rem;">
        <%= simple_form_for Edtracker.new do |f| %>
          <div class='modal-body'>
            <%= f.label :topic, 'Topic *', style: 'color: #707070;' %>
            <%= f.input :topic, input_html: { style: 'width: 470px; height: 48px; border-radius: 28px !important;' }, label: false, required: true %> <br>
        
            <%= f.label :notes, 'Notes', style: 'color: #707070;' %>
            <%= f.input :notes, input_html: { style: 'width: 470px; height: 190px; border-radius: 12px !important;' }, label: false %>
            <%#= f.label :resources, 'Resources *' %>
            <%#= f.input :resources, label: false %>
        
            <%= f.label :link, 'Link', style: 'color: #707070;margin-top:20px;' %>
            <%= f.input :link, input_html: { style: 'width: 470px; height: 100px; border-radius: 12px !important;' }, label: false %>
        
            <%= f.label :tag_list, 'Hashtags *', style: 'color: #707070; margin-top:20px;' %>
            <%= f.input :tag_list, input_html: { style: 'width: 470px; height: 48px; border-radius: 28px !important;' },  value: f.object.hashtag.to_s, label: false %>
        
            <%= hidden_field_tag "edtracker_type", "I want to learn" %>
          </div>
        
          <div class="form-group" style="margin-top: 30px; margin-bottom: 30px;">
            <%= f.button :submit, 'Submit', class: 'btn btn-custom btn-block custom-btn-sm', style: 'width: 200px; height: 40px; margin-left: 30%; color: white !important; margin-top:-35px;' %>
          </div>
        <% end %>
      
      </div>
    </div>
  </div>
</div>






<div class="modal fade" id='edtrackerModal2' tabindex='-1' role='dialog' aria-labelledby='NoteModalLabel' aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class="modal-content" style="min-width: 550px;padding: 20px; border-radius: 2%;">
      <div class="modal-header d-flex justify-content-center position-relative" style="border-bottom: none;">
        <h5 class="modal-title text-black" id="edtrackerModal" style="margin-left: auto; margin-top: 2rem; justify-content: center; font-size:26px;font-style:Cako;font-weight:400; line-height:32px;">
          I'm currently learning        
        </h5>
        <button style="margin-top: -130px; margin-right: -45px;" type="button" onclick="kill_model()" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div style="margin-top: 1rem;">
        <%= simple_form_for Edtracker.new do |f| %>
          <div class='modal-body'>
            <%= f.label :topic, 'Topic *', style: 'color: #707070;' %>
            <%= f.input :topic, input_html: { style: 'width: 470px; height: 48px; border-radius: 28px !important;' }, label: false, required: true %> <br>
        
            <%= f.label :notes, 'Notes', style: 'color: #707070;' %>
            <%= f.input :notes, input_html: { style: 'width: 470px; height: 190px; border-radius: 12px !important;' }, label: false %>
            <%#= f.label :resources, 'Resources *' %>
            <%#= f.input :resources, label: false %>
        
            <%= f.label :link, 'Link', style: 'color: #707070;margin-top:20px;' %>
            <%= f.input :link, input_html: { style: 'width: 470px; height: 100px; border-radius: 12px !important;' }, label: false %>
        
            <%= f.label :tag_list, 'Hashtags *', style: 'color: #707070; margin-top:20px;' %>
            <%= f.input :tag_list, input_html: { style: 'width: 470px; height: 48px; border-radius: 28px !important;' },  value: f.object.hashtag.to_s, label: false %>
        
            <%= hidden_field_tag "edtracker_type", "I'm currently learning" %>
          </div>
      
          <div class="form-group" style="margin-top: 30px; margin-bottom: 30px;">
            <%= f.button :submit, 'Submit', class: 'btn btn-custom btn-block custom-btn-sm', style: 'width: 200px; height: 40px; margin-left: 30%; color: white !important; margin-top:-35px;' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id='edtrackerModal3' tabindex='-1' role='dialog' aria-labelledby='NoteModalLabel' aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class="modal-content" style="min-width: 550px;padding: 20px; border-radius: 2%;">
      <div class="modal-header d-flex justify-content-center position-relative" style="border-bottom: none;">
        <h5 class="modal-title text-black" id="edtrackerModal" style="margin-left: auto; margin-top: 2rem; justify-content: center; font-size:26px;font-style:Cako;font-weight:400; line-height:32px;">
          I learned
        </h5>
        <button style="margin-top: -130px; margin-right: -45px;" type="button" onclick="kill_model()" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div>
        <%= simple_form_for Edtracker.new do |f| %>
            <div class='modal-body'>
              <%= f.label :topic, 'Topic *', style: 'color: #707070;' %>
              <%= f.input :topic, input_html: { style: 'width: 470px; height: 48px; border-radius: 28px !important;' }, label: false, required: true %> <br>
          
              <%= f.label :notes, 'Notes', style: 'color: #707070;' %>
              <%= f.input :notes, input_html: { style: 'width: 470px; height: 190px; border-radius: 12px !important;' }, label: false %>
              <%#= f.label :resources, 'Resources *' %>
              <%#= f.input :resources, label: false %>
          
              <%= f.label :link, 'Link', style: 'color: #707070;margin-top:20px;' %>
              <%= f.input :link, input_html: { style: 'width: 470px; height: 100px; border-radius: 12px !important;' }, label: false %>
          
              <%= f.label :tag_list, 'Hashtags *', style: 'color: #707070; margin-top:20px;' %>
              <%= f.input :tag_list, input_html: { style: 'width: 470px; height: 48px; border-radius: 28px !important;' },  value: f.object.hashtag.to_s, label: false %>
          
              <%= hidden_field_tag "edtracker_type", "I learned" %>
            </div>
        
            <div class="form-group" style="margin-top: 30px; margin-bottom: 30px;">
              <%= f.button :submit, 'Submit', class: 'btn btn-custom btn-block custom-btn-sm', style: 'width: 200px; height: 40px; margin-left: 30%; color: white !important; margin-top:-35px;' %>
            </div>
          <% end %>
          
      </div>
    </div>
  </div>
</div>




<script>
  function kill_model() {
    // window.location.reload();
  }
</script>

app/views/modals/_edit_note_modal.html.erb
<head><script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<div class="modal fade" id='editNoteModal' tabindex='-1' role='dialog' aria-labelledby='newNoteModalLabel'
  aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-contentuplod'>
      <div class="modal-header d-flex justify-content-center position-relative" style="border-bottom: none;">
        <h5 class="modal-title" id="newNoteModalLabel"
          style="margin-left: 47%; margin-right: auto; margin-top: 2rem;font-size:26px;font-weight:400;font-family:Cako;">Edit</h5>
        <button id="close-button" style="position: absolute; top: 5px;right: 0px; margin-right: 0px;"  type = 'button' class = 'close' data-dismiss = 'modal' style = 'color: white' aria-label = 'Close'>
           <span aria-hidden="true">×</span>
        </button>
      </div>
      <div>
        <%= simple_form_for @note, :html => {:multipart => true} do |f| %>
          <div class="modal-body row" style="padding: 5rem;">
            <div class="col-md-6" style=" border-style: dotted;
              border-width: 2px;
              border-color: #707070;
              color: #707070;
              border-radius: 15px;">
                <div class='upload-create-note'>
                  <div class='image-upload text-center' style="margin-top: 17%;">
                    <label for="file-input">
                      <div style="text-align: center;">
                        <%= image_tag @note.image.url, class: 'logo-image', id: 'img_prev' %>
                        <%= f.file_field :image, :input_html => {:onchange => 'readURL(this)'} %>

                        <p style="color: black; font-weight: 600; font-size: 12px; margin-top: 5px;">
                        Upload your image here
                        </p>

                  
                      </div>
                    </label>
                  </div>
                </div>
              </div>
              <!-- Right column for form fields -->
              <div class="col-md-6">
                <%= f.label :title, 'Title *' , style: 'color: #707070; font-weight: 400; font-size: 16px;' %>
                <%= f.input :title, label: false, required: true %>
                <%= f.label :body, 'Notes *' ,style: 'color: #707070; font-weight: 400; font-size: 16px; margin-top: 8%;' %>
                <span id='body-count' style="color: #707070; font-weight: 400; font-size: 16px; padding: 0; margin: 0;"> 0/650 </span>
                <%= f.input :body, maxlength: 650, label: false, placeholder: 'No more than 650 characters' ,input_html: { id: 'body-field' , rows: 7, class: 'custom-textarea' , style: 'padding: 10px 10px 30px 10px; border-radius: 15px !important;' } %>
                  <script>
                    $("#body-field").on("keyup", function () {
                      var length = $(this).val().length;
                      $("#body-count").html(length + '/650');
                    });
                  </script>
                  <div style="margin-top: 11%; margin-right:70%;">
                  <%= f.label :tag_list, 'Hashtags *', style: 'color: #707070; font-weight: 400; font-size: 16px; display: block;margin-right: 20px; width:59%;' %>
                  <%= f.label :tag_list, 'Please use # for the tags', style: 'color: #999999; font-weight: 400; font-size: 12px; width: 91%; display: block;margin-top: -10px;' %>
                </div>
                
                <%= f.input :tag_list, value: f.object.tag_list.to_s, label: false, required: true %>
              </div>
            </div>
            <div class="form-group" style="margin-top: 30px; margin-bottom: 30px;">
              <%= f.button :submit, 'Edit Picnotes' , class: 'btn btn-custom btn-block custom-btn-sm' ,id: 'create-picnotes-btn',remote: true,
                style: 'width: 370px; height: 40px; margin-left: 37%;color: white !important; background-color: #BC171D; border-radius: 30px;' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
 
$(document).ready(function() {
  $('#close-button').on("click", function (e) {
    if (confirm("You didn't share your Picnotes. Are you sure you want to leave without posting?")) {
      location.reload();
    } else {
      e.preventDefault();
    }
  });
});

</script>

<style>
  .modal-contentuplod {
    right: 360px;
    position: relative;
    display: flex;
    flex-direction: column;
    width: 1200px;
    color: var(--bs-modal-color);
    pointer-events: auto;
    background-color: white;
    background-clip: padding-box;
    border: var(--bs-modal-border-width) solid var(--bs-modal-border-color);
    border-radius: 15px;
    outline: 0;
    hright: 689px;
  }
  .upload-create-note {
    padding: 10px;
    margin-top: 15%;
    margin-bottom: 20px;
    border-radius: 5px;
  }
  .custom-textarea::placeholder {
    color: black;
    /* Change this to the desired color */
    opacity: 1;
    /* Ensure the placeholder is fully opaque */
    transform: translateY(5px);
    /* Adjust this value to move the placeholder down */
  }
  .custom-textarea {
    padding: 10px 10px 30px 10px;
    /* Add extra bottom padding to move the text down */
    border-radius: 15px !important;
    color: black;
  }
</style>


<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        console.log(e.target.result);
        $('#img_prev')
          .attr('src', e.target.result)
          .width(200)
          .height(200)
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/modals/_edit_note_reference_modal.html.erb
<div class = "modal fade" id = 'editReferenceModal' tabindex='-1' role = 'dialog' aria-labelledby = 'editReferenceModalLabel' aria-hidden='true'>
  <div class = 'modal-dialog' role = 'document'>
    <div class = 'modal-content'>
      <div class = 'modal-header new-modal-header'>
        <h5 class = 'modal-title' id = 'editReferenceModalLabel' style = 'color:white;'> Edit Reference </h5>
        <button type = 'button' style = 'color: white;'class = 'close' data-dismiss = 'modal' aria-label = 'Close'>
          <span aria-hidden = 'true'> &times; </span>
        </button>
      </div>

      <div>
        <%= simple_form_for([@note, @reference], remote: true, :html => {:id => 'reference_form'}) do |f| %>
          <div>
            <%= f.input :file_type, collection: Reference::TYPE %>
            <div id="generic-content">
              <%= f.input :title %>
              <%= f.input :author %>
              <%= f.input :link %>
            </div>
            <div id="image-source-content">
              <%= f.input :image_source , as: :text, :input_html => { :cols => 5, :rows => 5 } %>
              <%= f.input :link %>
            </div>

          </div>
          <div class = 'form-btn-container text-center'>
            <%= f.button :submit, :class => 'blue-appearance-btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_follow_modal.html.erb
<div class="modal fade" id='followModal' tabindex='-1' role='dialog' aria-labelledby='editSessionModalLabel'
  aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <div class="modal-header d-flex justify-content-center position-relative" style="border-bottom: none;">
        <h5 class="modal-title" id="editSessionModalLabel"
          style="margin-left: 26%; margin-right: auto; margin-top: 2rem;">Follow Lifelong Learners</h5>
        <button style="margin-top: -90px; margin-right: -23px;" type="button" onclick="kill_model()" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="table-follow-modal">
        <div id="result" style="margin-left: 5px;color: green; overflow: auto;"></div>
        <div class='modal-body conatiner'
          style=' padding: 10px; border-radius: 0.25em; margin-top: 10px; margin-bottom: 10px;'>
          <div style="max-height: 370px; overflow: auto; position: relative;">
            <table class="table-condensed">

              <form class="d-flex mx-2 position-relative">
                <%= form_tag(feed_index_path, method: "get", remote: true, class: "d-flex mx-2 position-relative") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Enter name", id: "search-user", class: "form-control pl-4", style: "height: 1%;" %>
                <div class="search-icon position-absolute" style="right: 4px; transform: translateY(-50%); cursor: pointer; z-index: 1; top: 20px;">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 50 50">
                    <path d="M 21 3 C 11.622998 3 4 10.623005 4 20 C 4 29.376995 11.622998 37 21 37 C 24.712383 37 28.139151 35.791079 30.9375 33.765625 L 44.085938 46.914062 L 46.914062 44.085938 L 33.886719 31.058594 C 36.443536 28.083 38 24.223631 38 20 C 38 10.623005 30.377002 3 21 3 z M 21 5 C 29.296122 5 36 11.703883 36 20 C 36 28.296117 29.296122 35 21 35 C 12.703878 35 6 28.296117 6 20 C 6 11.703883 12.703878 5 21 5 z"></path>
                  </svg>
                </div>
              <% end %>
              </form>


              <div id="search-results"></div>
              <div>
                <div id="original-results">
                  <% top_user = top_writer %>
                  <% if !current_user.follow?(top_user) && current_user.id != top_user.id %>
                  <tr id=<%= top_user.id * top_user.id %>>
                    <td>
                      <%= image_tag current_user.avatar.url || 'myavtar.png', style: 'width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;' %>
                      <%= top_user.first_name + " " + top_user.last_name %>
                    </td>
                    <td>
                      <button style="background: white;border: none;color: #BC171D;" class="follow" target=<%= top_user.id %> id=<%= top_user.id %>> follow</button>
                    </td>
                  </tr>
                  <% end %>
                  <% User.all.each do |user| %>
                    <% if user_signed_in? %>
                    <% if current_user.id != user.id %>
                    <% if !current_user.follow?(user) && !(user.id == top_user.id) %>
                    <tr id=<%= user.id * user.id %>>
                      <td >
                        <%= image_tag 'myavtar.png', style: 'width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;' %>
                        <%= user.full_name %>
                      </td>
                      <td>
                        <button style="background: white;border: none;color: #BC171D;" class="follow" target=<%= user.id %> id=<%= user.id %>> follow</button>
                      </td>
                    </tr>
                    <% end %>
                    <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
             

            </table>
          </div>

          <div class="form-group" style="margin-top: 10px;">
            <%= form_with url: feed_index_path, method: :get, local: true do %>
              <button type="submit" class="btn btn-custom btn-block custom-btn-sm" style="color:white !important;">Done</button>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
  
</div>


<script>
  function kill_model() {
   // window.location.reload();
  }
</script>

<style>
  .bold {
    color: #B8E314;
  }
  #search-user {
    border: 1px solid;
    border-radius: 5px;
    margin-right: 3px;
  }
</style>
<script>
  $(document).ready(function () {
    $('#search-user').on("input", function () {
      var search_val = $('#search-user').val();
      var sTimeOut = setTimeout(function () {
        $.ajax({
          type: "GET",
          url: "feed/user_search",
          // dataType:"json",
          data: { search: search_val },
          success: function (result) {
            // console.log(result)
            // alert(result);
          }
        })
      }, 3000);
    })
  })
  $(document).ready(function () {
    $('.follow').click(function (event) {
      var id = $(event.target).attr('target');
      $('#result').html('<p>Request Completing </p>');
      $.ajax({
        url: '/followunfollow',
        type: 'post',
        async: false,
        data: {
          followed_id: id
        },
        success: function (request) {
          $("#" + id).addClass("bold");
          $('#result').html('<p> </p>');
          $("#" + id * id).hide();
          $("#" + id).hide();
          $('#result').html('<p>Request Completed Successfully</p>');
        },
        error: function (xhr) {
        }
      });
    })
  });
  $(document).ready(function () {
    $('.unfollow').click(function (event) {
      var id = $(event.target).attr('target1');
      $.ajax({
        url: '/unfollow',
        type: 'post',
        async: false,
        data: {
          id: id
        },
        success: function (request) {
          $("#" + id).addClass("bold");
        },
        error: function (xhr) {
        }
      });
    })
  });
</script>
<style>
  .search-iconfollow{
    right: 15px;
    top: 0.3%;
    transform: translateY(-50%);
  }
</style>

app/views/modals/_new_session_modal.html.erb
<div class = "modal fade" id = 'newSessionModal' tabindex='-1' role = 'dialog' aria-labelledby = 'newSessionModalLabel' aria-hidden='true'>
  <div class = 'modal-dialog' role = 'document'>
    <div class = 'modal-content'>
      <div class = 'modal-header new-modal-header'>
        <h5 class = 'modal-title' id = 'newSessionModalLabel' style = 'color: white'> Sign In </h5>
        <button type = 'button' class = 'close' data-dismiss = 'modal' aria-label = 'Close'>
          <span aria-hidden = 'true'> &times; </span>
        </button>
      </div>

      <div class = 'modal-body'>
        <div class = 'text-center'>
          <%= image_tag 'logo-clean.png', class: 'intro-image' %>
        </div>
       <div class="container">

        <a href=  <%=	 user_facebook_omniauth_authorize_path %> , class="fb btn">
          <i class="fa fa-facebook" style="text-align: left ;color:#ffffff;"></i>&nbsp;&nbsp; &nbsp;&nbsp; Connect with Facebook
        </a>
        <br/>
        <a href=  <%=  user_google_oauth2_omniauth_authorize_path %> , class="fb btn" style="margin-top: 7px;background: #1a73e8;">
          <i class="fa fa-google" style="text-align: left ;color:#ffffff;"></i>&nbsp;&nbsp; &nbsp;&nbsp; Connect with Google
        </a>
      </div>
        <%= simple_form_for :session, url: session_path do |f| %>

          <%#= link_to' "&nbsp; Continue with Facebook', user_facebook_omniauth_authorize_path, class: ' fa fa-facebook fb btn fab fa fa-facebook', style:"text-align: left ;color:#ffffff;"
          %>

         <p style="    text-align: center;
             margin-top: 7px;
             margin-bottom: 0px;
             border-bottom-width: 0px;
             padding-bottom: 0px;"> OR</p>
          <%= f.label 'Email' %>
          <%= f.input :email, label: false %>

          <%= f.label 'Password' %>
          <%= f.input :password, label: false %>
          <%= link_to "(forgot password)", new_password_reset_path %>

          <div class = 'form-btn-container'>
            <%= f.button :submit, 'Sign In', :class => 'blue-appearance-btn' %>
          </div>

          &nbsp;&nbsp;
        <% end %>


      </div>
    </div>
  </div>
</div>